sudo: required

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
  # C++14
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
install: 
  # C++14
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++-5; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90; fi

matrix:
  exclude:
    - os:       osx
      compiler: gcc

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release


script:
  - python src/main.py -i simple_test/config -o simple_test/generated_cpp/xml -f xml -l cpp -side server -data simple_test/data_xml -data_out simple_test/assets
  
  - cd simple_test
  - mkdir build_xml_server
  - cd build_xml_server
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DBUILD_XML=ON -DBUILD_JSON=OFF -DBUILD_SIDE=SERVER 
  - make
  - ./test_mlc_xml ../
  - cd ..

  - cd simple_test
  - mkdir build_xml_client
  - cd build_xml_client
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DBUILD_XML=ON -DBUILD_JSON=OFF -DBUILD_SIDE=CLIENT 
  - make
  - ./test_mlc_xml ../
  - cd ..


  - python src/main.py -i simple_test/config -o simple_test/generated_cpp/json -f json -l cpp -side client -data simple_test/data_json -data_out simple_test/assets

  - mkdir build_json_server
  - cd build_json_server
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DBUILD_XML=OFF -DBUILD_JSON=ON -DBUILD_SIDE=SERVER
  - cmake --build .
  - ./test_mlc_json ../
  - cd ..

  - mkdir build_json_client
  - cd build_json_client
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DBUILD_XML=OFF -DBUILD_JSON=ON -DBUILD_SIDE=CLIENT
  - cmake --build .
  - ./test_mlc_json ../
  - cd ..